name: orders_accountant
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_native_splash: ^2.2.11
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  go_router: ^10.0.0
  flutter_displaymode: ^0.6.0
  shared_preferences: ^2.0.15
  internet_connection_checker: ^1.0.0+1
  gap: ^3.0.0
  modal_bottom_sheet: ^2.1.0
  intl: ^0.18.0
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  supabase_flutter: ^2.2.0
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  mocktail: ^0.3.0
  flutter_appauth: ^6.0.1
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  animated_check: ^1.0.5
  settings_ui: ^2.0.2
  bloc_test: ^9.1.5
  animated_tree_view: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.7.1
  test: ^1.24.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  image_path: "assets/images/order_accountant_launcher_icon.png"

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: PangramBlack
      fonts:
        - asset: assets/fonts/Pangram-Black.otf
# COMMANDS
# flutter pub run flutter_launcher_icons:main
# flutter pub run flutter_native_splash:create
